# Generated by Django 5.0.6 on 2024-05-18 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_remove_customer_firstname_remove_customer_lastname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='firstname',
            field=models.CharField(default='Not specified', help_text='First name', max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='lastname',
            field=models.CharField(default='Not specified', help_text='Last name', max_length=30),
        ),
        migrations.AddField(
            model_name='employee',
            name='firstname',
            field=models.CharField(default='Not specified', help_text='First name', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='lastname',
            field=models.CharField(default='Not specified', help_text='Last name', max_length=30),
        ),
    ]
