# Generated by Django 5.0.6 on 2024-05-19 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_customer_time_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='time_zone',
            field=models.CharField(default='UTC', help_text='Time zone', max_length=50),
        ),
    ]
