# Generated by Django 5.0.6 on 2024-05-20 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0017_remove_complete_order_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='complete_order',
            name='order',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='cars.order'),
        ),
    ]
