# Generated by Django 5.0.6 on 2024-05-18 12:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_companyinfo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='firstname',
            field=models.CharField(default='Not specified', help_text='First name', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='lastname',
            field=models.CharField(default='Not specified', help_text='Last name', max_length=30),
        ),
        migrations.AddField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(default='Not specified', help_text='Phone number', max_length=15),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(default='Not specified', help_text='Position in company', max_length=100),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='Not specified', help_text='First name', max_length=20)),
                ('lastname', models.CharField(default='Not specified', help_text='Last name', max_length=30)),
                ('phone_number', models.CharField(default='Not specified', help_text='Phone number', max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
