# Generated by Django 5.0.6 on 2024-05-18 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_customer_firstname_customer_lastname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='lastname',
        ),
    ]
