# Generated by Django 5.0.6 on 2024-05-19 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_employee_time_zone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Vacancy name', max_length=30)),
                ('title', models.CharField(help_text='Vacancy title', max_length=200)),
                ('description', models.CharField(help_text='Vacancy description', max_length=2000)),
            ],
        ),
    ]
