# Generated by Django 5.0.6 on 2024-05-20 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0012_car_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='date_delivery',
        ),
        migrations.CreateModel(
            name='Complete_Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.IntegerField(help_text='Total price of order')),
                ('date_delivery', models.DateField(help_text='Date of delivery')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cars.order')),
            ],
        ),
    ]
