# Generated by Django 5.0.6 on 2024-05-22 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0019_remove_review_order_alter_review_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
